### PR TITLE
Changes to finish getting WarpNetwork working in 1.6

### PR DESCRIPTION
**Pull request by NermNermNerm**
It looks like the master branch was on its way to working in 1.6, but work stopped before it was fully working.  Hopefully this will at least get it playable if not all-the-way working.

### CODE REVIEW

**Comment by NermNermNerm** [comment]
I think I have the Rod of Return working fully, but interactions with the warp totems don't work at all.  I'm stumped as to how it ever did.  I can see code in WarpHandler calling RegisterTileAction, but I can't find any code that would actually add the tile actions to the map.

I don't want to take up much of your time, as I know you've got other life priorities right now, but if you could give me a hint...

**Comment by NermNermNerm** [comment]
I dug up the old code that added the tile actions, put it back, banged on it a little, and now it seems to work.  What's untested is mod integration.  I've tested it with SVE, and it works fine with Grandpa's Farm.  Beyond that, I don't know.   Clearly you were in the middle of a broad effort when you left off.  Some of the stuff I do in this PR undoes recent commits, as I don't know where you were going.  In my defense, I'd point out that WarpNetwork is a really fun mod and even a wonky, not-quite-compatible-with-other-mods WarpNetwork is better than none!

**Comment by tlitookilakin** [comment]
Thanks a bunch for your hard work! Sorry for the wait, I was away from home for several days and didn't have access to my computer. I'll take a look at it

**Comment by tlitookilakin** [comment]
> I think I have the Rod of Return working fully, but interactions with the warp totems don't work at all. I'm stumped as to how it ever did. I can see code in WarpHandler calling RegisterTileAction, but I can't find any code that would actually add the tile actions to the map.
> 
> I don't want to take up much of your time, as I know you've got other life priorities right now, but if you could give me a hint...

Originally it relied on SMAPI patches from Aerocore, but in the process of ripping out all the old spaghetti I decided to get rid of that, and hadn't gotten around to replacing it yet.

The introduction of totem stuff to SpaceCore combined with the new minecart network system meant that huge swaths of the original features were basically obsolete, and at the time 1.6's launch date was closing in fast, so that's about where I abandoned it. There's probably a lot of half-finished stuff because of that.

If we can get it to a mostly-working state, I'd be happy to publish it as an interim release.

Because so much of the code is obsolete and, to be frank, horrible legacy spaghetti (since warp network was only my second c# project, and subsequent refactors can only do so much), my long-term plan is to split it into 3 mods:
 - A legacy mod to handle all the old-format assets for mods that aren't getting updates in 1.6
 - A new mod to add a custom travel network for all the warp points, and special handling for the farm, as well as return scepter features. Possibly totem redirection?
 - A new mod that is just the nice UI, which can be used with all travel networks

**Comment by NermNermNerm** [comment]
After having done all the fiddling to get it to work and all, I did a little bit more reading in the Posts for Warp Network, and I see a recommendation to use [Magic Sceptre](https://www.nexusmods.com/stardewvalley/mods/8169?tab=description).  I think that might explain the small number of downloads my test release got.

I wonder if maybe the right thing to do is to just cede the field to that mod and focus efforts on mods that don't have a ready replacement.

**Comment by tlitookilakin** [comment]
Letting somebody else maintain the code would definitely be less work :P

**Comment by NermNermNerm** [comment]
After a couple days of pondering, my vote would be to go ahead and release what we've got here, and change the mod description to "THIS MOD IS TOTALLY STALE AND NOT MAINTAINED AND YOU SHOULD USE Magic Sceptre et.al.!"

The idea of releasing it is for somebody who's truly a die-hard fan or just want to stick with what they know.  Taking the PR also means that if somebody really thinks WarpNetwork is a better basis for whatever it is they're doing, they can at least read and debug the code.  The added code in this PR is really just the old code, brought back from the git.crypt, so it's not like I've got a pile of ego riding on this.

**Pull request merged**
